version: '3'

services:
  # CTSWS Apache Tomcat container
  ctsws:
    restart: unless-stopped
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ${CTSWS_IMAGE}
    container_name: ctsws
    # expose:
    #   - "8080"
    ports:
      - "8082:8080"
    environment:
      - JAVA_OPTS=-Xmx1g
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
      - CTSWS_SERVER_USERNAME=${CTSWS_SERVER_USERNAME}
      - CTSWS_SERVER_PASSWORD=${CTSWS_SERVER_PASSWORD}
    volumes:
      - ./chemaxon/licenses/license.cxl:/root/.chemaxon/licenses/license.cxl
