version: '3'

services:

  # Apache Tomcat container
  cts-tomcat:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: cts-tomcat-testing
    container_name: cts-tomcat-testing
    # expose:
    #   - "8080"
    ports:
      - "8082:8080"
    environment:
      - JAVA_OPTS=-Xmx1g
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
      - CHEMAXON_LICENSE_URL=/root/.chemaxon/licenses/license.cxl
      - SERVER_USERNAME=${SERVER_USERNAME}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - CTSWS_VERSION=1.0
    volumes:
      # - .:/src
      - ./ctsws/settings.xml:/root/.m2/settings.xml
      - ./ctsws/repository:/root/.m2/repository
      - ./chemaxon/license.cxl:/root/.chemaxon/licenses/license.cxl
    #   - ./secrets/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    #   - ./secrets/tomcat/webapps:/usr/local/tomcat/webapps
    #   - ./secrets/tomcat/chemaxon/licenses:/home/tomcat/.chemaxon/licenses