version: '3'

services:
  # CTSWS Apache Tomcat container
  ctsws:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: ${CTSWS_IMAGE:-ghcr.io/quanted/ctsws:docker}
    container_name: ctsws
    # expose:
    #   - "8080"
    ports:
      - "8082:8080"
    environment:
      - JAVA_OPTS=-Xmx1g
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
      - CHEMAXON_LICENSE_URL=/root/.chemaxon/licenses/license.cxl
      - SERVER_USERNAME=${SERVER_USERNAME}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
    volumes:
      - ./chemaxon/license.cxl:/root/.chemaxon/licenses/license.cxl
